services:
  postgres:
    image: custompostgres
    build: ./db
    container_name: dev_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: test_database
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data #The volume named exactly "postgres_data" can be troublesome with init scripts, rename it.

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: dev_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    ports:
      - "8088:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pg_data:
  pgadmin_data: